apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
  namespace: k8s-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    # - { key: app, operator: In, values: [second-app, first-app] }
    # - key: app
    #   operator: In
    #   values:
    #     - second-app
    #     - first-app
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: stewartsum/kub-first-app:2
